### ISSUE TITLE
license question / sources location

### ISSUE THREAD

**Issue by herrold** [OutbreakInc/LogiblockPlatform#2]
I see in the file: package.json

a License of: CC-SA-BY-3.0

but am unclear as to the location from which to retrieve some of the sources to rebuild, eg, GalagoServer-linux64 -- it seems to be a compiled binary and in checking the hierarchy at:
  https://github.com/OutbreakInc

I do not see the relevant sources

**Comment by kuym** [comment]
We don't release sources for GalagoServer, and the license property in the npm `package.json` file was intended to refer to the Node.js component of the repository - `SDK.js`.  I think licensing binary blobs with CC-BY-SA is sensible, as it doesn't mandate that they (or anything they link to) be in source form like GPL does, but it's still possible to reuse them as opaque components in other products, both commercial and non-commercial, as long as there's attribution.
