### ISSUE TITLE
start failure missing moduleverse items per (posibly old) web doco

### ISSUE THREAD

**Issue by herrold** [OutbreakInc/LogiblockPlatform#3]
I am following the (perhaps stale) instructions at:
   http://logiblock.com/pages/ide

I do not see an INSTALL, README, or similar file in the checkout

I pull from git just, and then roll a date-versioned tarball locally -- here: LogiblockPlatform-20130723.tgz 
of the: ./LogiblockPlatform/ directory

version pulled is: 92226dbda1360363f21d2d4bd0e57a9720ab2774

I extract the tarball, and set up a new project directory: ./acme/

I have a late enough version of: node.js (see bottom of the listing)

I move into that directory, and then using the relative path up and over to the bin directory, attempt to '--init' the new project

It dies as shown;  I assume something provided by 'moduleverse' is needed, but the documentation page does not mention that requirement

SIDE MATTER:  there is a comment:

>   In all examples, you may also pass an optional argument containing the project's path.

but no example of doing such -- could you please add such an example?

Thank you

-- Russ herrold

[herrold@centos-6 LogiblockPlatform]$ ls -al  
drwxrwxr-x.   4 herrold herrold   4096 Jul 23 13:39 LogiblockPlatform  
-rw-rw-r--.   1 herrold herrold 147428 Jul 23 13:40 LogiblockPlatform-20130723.tgz  
[herrold@centos-6 LogiblockPlatform]$ tar zxf LogiblockPlatform-20130723.tgz  
[herrold@centos-6 LogiblockPlatform]$ mkdir acme  
[herrold@centos-6 LogiblockPlatform]$ cd acme  
[herrold@centos-6 acme]$ node ../LogiblockPlatform-20130723/bin/SDK.js --init

module.js:340
    throw err;
          ^
Error: Cannot find module 'moduleverse'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/herrold/vcs/git/LogiblockPlatform/LogiblockPlatform-20130723/bin/SDK.js:6:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
[herrold@centos-6 acme]$ rpm -qa node*
nodejs-0.10.12-1.orc6.x86_64
nodejs-docs-0.10.12-1.orc6.noarch
nodejs-packaging-0.10.12-1.orc6.noarch
[herrold@centos-6 acme]$

**Comment by kuym** [comment]
By tradition, repositories containing Node.js code don't include checked-in npm dependencies.  The docs refer to a [moduleverse package](http://moduleverse.com/v1/modules/logiblock/platform/0.9.16/gz), which includes pre-resolved npm dependencies.  If you'd like to run from source, you'll need to `cd` to the **bin** directory inside (where **package.json** is) and run `npm update -d` to fetch npm packages.

**Comment by herrold** [comment]
Shall I file separately:

SIDE MATTER: there is a comment:

```
In all examples, you may also pass an optional argument containing the project's path.
```

but no example of doing such -- could you please add such an example?

# 

Primary matter:

hmmm -- Node.js 'traditions' are not familiar to me.  It would seem that this is a step to document at the cited page ...

Takeaway:  one also needs to install and run that npm command ... 

[herrold@centos-6 LogiblockPlatform-20130723]$ npm update -d
bash: npm: command not found
[herrold@centos-6 LogiblockPlatform-20130723]$ pwd
/home/herrold/vcs/git/LogiblockPlatform/LogiblockPlatform-20130723
[herrold@centos-6 LogiblockPlatform-20130723]$ yum -q provides *bin/npm
npm-1.2.17-5.el6.noarch : Node.js Package Manager
Repo        : epel
Matched from:
Filename    : /usr/lib/node_modules/npm/bin/npm
Filename    : /usr/bin/npm

and once I install 'npm' and run it as indicated, the problem should disappear

... an hour later ... goodness, there are a HUGE number of dependencies to get npm happy

**Comment by kuym** [comment]
It's not necessary to document because you're not following the normal instructions - you cloned from github which is a developer workflow. npm is not a dependency of this project unless you're developing it.  Moreover, it might be simpler to install it along with node from pre-built binaries at http://nodejs.org

I will put an example of the optional path argument to `SDK.js` up, though. _(done, see the [getting started guide](https://github.com/OutbreakInc/Galago/wiki/Getting-started-guide))_
